config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root to: "pages#home"

  resources :cars, only: [ :index, :show ] do
    resources :reviews, only: :create
    resources :favourites, only: :create
  end

  resources :favourites, only: [:index, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :owner
  has_many :reviews
  has_many :favourites

  validates :brand, :model, :year, :fuel, presence: true
  validates :year, numericality: { only_integer: true }
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :car
end

app/models/owner.rb
class Owner < ApplicationRecord
  has_many :cars
  

  validates :nickname, presence: true
  validates :nickname, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :car
  validates :comment, :rating, presence: true
  validates :rating, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
  end

  def show
    @car = Car.find(params[:id])
    @review = Review.new
    @favourite = Favourite.new
  end
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  def index
    @favourites = Favourite.all
  end

  def create
    @favourite = Favourite.new
    @car = Car.find(params[:car_id])
    @favourite.car = @car
    if @favourite.save
      redirect_to car_path(@car)
    else
      render 'cars/show', status: :unprocessable_entity
    end
  end

  def destroy
    @favourite = Favourite.find(params[:id])
    @favourite.destroy
    redirect_to favourites_path, status: :see_other
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @car = Car.find(params[:car_id])
    @review = Review.new(review_params)
    @review.car = @car
    # @review.car_id = @car.id
    if @review.save
      redirect_to car_path(@car)
    else
      render 'cars/show', status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cars/index.html.erb
<h1>Showroom</h1>
<% @cars.each do |car| %>
  <h2><%= car.brand %></h2>
  <h3><%= car.model %></h3>
  <p><%= car.created_at.strftime("%a %b %e at %l%M %p") %></p>
  <div><%= car.owner.nickname %></div>
  <%= link_to "More details", car_path(car) %>
<% end %>

app/views/cars/show.html.erb
<h2><%= @car.brand %></h2>
<h3><%= @car.model %></h3>
<p><%= @car.fuel %></p>
<p><%= @car.year %></p>

<div>
  <%= simple_form_for [@car, @review] do |f| %>
    <%= f.input :comment, label: false, placeholder: "Coment here..." %>
    <%= f.input :rating, collection: 0..5, label: false %>
    <%= f.submit 'Add review' %>
  <% end %>
</div>

<% @car.reviews.each do |review| %>
  <p><%= review.comment %></p>
  <p><%= '⭐️' * review.rating %></p>
<% end %>

<% if @car.favourites.empty? %>
  <%= simple_form_for [@car, @favourite] do |f| %>
    <%= f.submit 'Save to my Garage' %>
  <% end %>
<% else %>
  <p>This car is in your garage!</p>
<% end %>

app/views/favourites/index.html.erb
<h1>My Garage</h1>

<% @favourites.each do |favourite| %>
  <p><%= favourite.car.brand %></p>
  <p><%= favourite.car.model %></p>
  <%= link_to "Remove from my garage", favourite_path(favourite), data: {turbo_method: :delete, turbo_confirm: "Do you really want to take the #{favourite.car.model} out of your garage?"} %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rails Awesome Garage" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div  class="banner" style="background-image: url(https://png.pngtree.com/background/20230410/original/pngtree-car-light-effect-smog-technology-background-picture-image_2385148.jpg);">
  <div class="banner-container">


    <h2>DREAM</h2>


    <h3>GARAGE</h3>
    <p>Your dream cars in one place</p>

    <div>
    <%=link_to "Showroom", cars_path, class: "btn btn-primary" %>
    <%= link_to "My Garage", favourites_path, class: "btn btn-secondary" %>
  </div>


  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "car logo.jpg"  %>

    <% end %>
    <div><h1 class="logo_text">DreamGarage.com</h1></div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">

          <%= link_to "Showroom", cars_path, class: "nav-link", style: "color: black;" %>
          </li>
          <li class="nav-item">
          <%= link_to "My Garage", favourites_path, class: "nav-link", style: "color: black;" %>

          </li>

          <!--li class="nav-item"-->
          <!--/li-->
      </ul>
    </div>
  </div>
</div>